[tool.poetry]
name = "course-project-2"
version = "0.1.0"
description = ""
authors = ["jacob zhuchkov <jacob1989@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
